# Sample input carried over from the original 2019 server.
EXAMPLE_FASTA = """\
>seq0
FQTWEEFSRAAEKLYLADPMKVRVVLKYRHVDGNLCIKVTDDLVCLVYRTDQAQDVKKIEKF
>seq1
KYRTWEEFTRAAEKLYQADPMKVRVVLKYRHCDGNLCIKVTDDVVCLLYRTDQAQDVKKIEKFHSQLMRLME LKVTDNKECLKFKTDQAQEAKKMEKLNNIFFTLM
>seq2
EEYQTWEEFARAAEKLYLTDPMKVRVVLKYRHCDGNLCMKVTDDAVCLQYKTDQAQDVKKVEKLHGK
>seq3
MYQVWEEFSRAVEKLYLTDPMKVRVVLKYRHCDGNLCIKVTDNSVCLQYKTDQAQDVK
>seq4
EEFSRAVEKLYLTDPMKVRVVLKYRHCDGNLCIKVTDNSVVSYEMRLFGVQKDNFALEHSLL
>seq5
SWEEFAKAAEVLYLEDPMKCRMCTKYRHVDHKLVVKLTDNHTVLKYVTDMAQDVKKIEKLTTLLMR
>seq6
FTNWEEFAKAAERLHSANPEKCRFVTKYNHTKGELVLKLTDDVVCLQYSTNQLQDVKKLEKLSSTLLRSI
>seq7
SWEEFVERSVQLFRGDPNATRYVMKYRHCEGKLVLKVTDDRECLKFKTDQAQDAKKMEKLNNIFF
>seq8
SWDEFVDRSVQLFRADPESTRYVMKYRHCDGKLVLKVTDNKECLKFKTDQAQEAKKMEKLNNIFFTLM
>seq9
KNWEDFEIAAENMYMANPQNCRYTMKYVHSKGHILLKMSDNVKCVQYRAENMPDLKK
>seq10
FDSWDEFVSKSVELFRNHPDTTRYVVKYRHCEGKLVLKVTDNHECLKFKTDQAQDAKKMEK
"""

# First columns of EXAMPLE_FASTA as aligned by each tool, shown in the home page hero.
# Taken from real runs of the pinned tools (seq0-seq5, columns 48-61).
HERO_ALIGNMENTS: dict[str, list[str]] = {
    "mafft": [
        "LVYRTDQAQDVKKI",
        "LLYRTDQAQDVKKI",
        "LQYKTDQAQDVKKV",
        "LQYKTDQAQDVK--",
        "VSYEMRLFGVQKDN",
        "LKYVTDMAQDVKKI",
    ],
    "muscle": [
        "LVYRTDQAQDVKKI",
        "LLYRTDQAQDVKKI",
        "LQYKTDQAQDVKKV",
        "LQYKTDQAQDVK--",
        "S-YEMRLFGVQKDN",
        "LKYVTDMAQDVKKI",
    ],
    "clustalw": [
        "--------LVYRTD",
        "--------LLYRTD",
        "--------LQYKTD",
        "--------LQYKTD",
        "SYEMRLFGVQ-KDN",
        "--------LKYVTD",
    ],
    "tcoffee": [
        "LVYRTDQAQDVKKI",
        "LLYRTDQAQDVKKI",
        "LQYKTDQAQDVKKV",
        "LQYKTDQAQDVK--",
        "-SYEMRLFGVQKDN",
        "LKYVTDMAQDVKKI",
    ],
}
